### ISSUE TITLE
_over_time function does not work / select correct data

### ISSUE THREAD

**Issue by bwplotka** [thanos-community/promql-engine#63]
New engine: 

![image](https://user-images.githubusercontent.com/6950331/193826876-90c66dd5-18f7-454a-9ed3-4eff521696ee.png)

Old engine:
![image](https://user-images.githubusercontent.com/6950331/193827011-e15184cd-ea00-42d7-bfe7-fbe69bf0e6ee.png)

**Comment by fpetkovski** [comment]
Hm, the queries are different no?

**Comment by fpetkovski** [comment]
Since you are using a very large range, I wonder if you might be running into something that was fixed in https://github.com/thanos-community/promql-engine/pull/50, specifically here:
https://github.com/thanos-community/promql-engine/blob/402d810ef56cf0d00b72f728483b4792883143a8/physicalplan/plan.go#L74-L75

**Comment by fpetkovski** [comment]
Closing this for now, I think it has been long fixed.
